name: Syntax_check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Help_test
      run: curl -s https://get.nextflow.io | bash && ./nextflow run phage.nf --help
    - name: fasta dry run
      run: |
          ./nextflow run phage.nf --fasta ./test-data/stub_genome.fasta -stub -profile stub --cores 2 --max_cores 2
