name: run_WtP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run_What_the_Phage
      run: curl -s https://get.nextflow.io | bash && ./nextflow run phage.nf -profile git_action,docker
